version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
        - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"